# flask-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  selector:
    matchLabels:
      app: flask-app
  replicas: 1
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: devopsheros137/flight-app-demo:2.5.8
        ports:
        - containerPort: 5000
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: creds
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: creds
              key: password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: creds
              key: db
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: creds
              key: host
---
# flask-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  selector:
    app: flask-app
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: configmap-creator
  namespace: default
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: configmap-creator-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: configmap-creator
  apiGroup: rbac.authorization.k8s.io